version: '3.7'
services:
  frontend:
    build: frontend/.
    ports:
      - "80:3000"
    restart: always
    links:
      - backend
  backend:
    build: backend/.
    ports:
      - "8000:80"
    restart: always